spring:
  profiles:
    active: local #默认为本地环境



jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer



mail:
  pass: ioiovjebgwvghdjf
  host: smtp.qq.com
  port: 25
  from: 1181639720@qq.com
  user: 1181639720

cos:
  appid: 1257281765
  secretid: AKIDY1IOJ2Jv78xlZEb1KSPBmCQTM3ZxlC3j
  secretkey: f9RYTEhz51mLo6EAvVt67xcaNzRhmfNw
  buckertname: gediao-1257281765
  prefix: mall-admin
